### ISSUE TITLE
Sounds great, but can't get it to work :-(

### ISSUE THREAD

**Issue by BeardedSimmo** [shauncampbell/homebridge-sky-plus-hd#1]
Thanks for the plugin but it doesn't want to play with my homebridge.  I've set up as per your instructions but all I get is this:

[10/30/2016, 2:39:31 PM] Loaded plugin: homebridge-sky-plus-hd
[10/30/2016, 2:39:31 PM] Registering accessory 'homebridge-sky-plus-hd.SkyPlusHDBox'
[10/30/2016, 2:39:31 PM] ---
C:\Users\PhilS\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:199
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (C:\Users\PhilS\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:199:31)
    at new Server (C:\Users\PhilS\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:49:23)
    at module.exports (C:\Users\PhilS\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:26:16)
    at Object.<anonymous> (C:\Users\PhilS\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

Is it something I'm doing wrong?

Cheers

**Comment by shauncampbell** [comment]
Can you attach a copy of your config.json? From what I can tell that error seems to be coming from homebridge itself rather than the plugin.

**Comment by BeardedSimmo** [comment]
Thanks Shaun, it's more than likely my config.json.  Here it is....

[config.txt](https://github.com/shauncampbell/homebridge-sky-plus-hd/files/560703/config.txt)

Changed .json to .txt so that I could add it.

**Comment by shauncampbell** [comment]
I think i see the problem. You've got the homebridge config inside the accessories tag. I think it should be more like this:

```
{
      "bridge": {
          "name": "Homebridge",
          "username": "CC:21:3E:E4:DE:43",
          "port": 51826,
          "pin": "031-45-154"
      },
      "description": "Configuration file for (e)xtended Domoticz platform.",
      "platforms": [
                {
                    "platform": "eDomoticz",
                    "name": "eDomoticz",
                    "server": "127.0.0.1",
                    "port": "8080",
                    "ssl": 0,
                    "roomid": 2,
                    "mqttenable": 1,
                    "mqttserver": "127.0.0.1",
                    "mqttport": "1883",
                    "mqttauth": 0,
                    "mqttuser": "",
                    "mqttpass": ""
                }
            ],
    "accessories": [
        {
            "accessory": "people",
            "name": "People",
            "people": [
                {
                    "name": "Person1",
                    "target": "192.168.0.5"
                },
                {
                    "name": "Person 2",
                    "target": "192.168.0.11"
                },
                {
                    "name": "Person 3",
                    "target": "192.168.0.12"
                }
            ],
            "threshold": 5
        },
        {
            "accessory": "SkyPlusHDBox",
            "name": "BSkyB",
            "ipAddress": "192.168.0.17",
            "region": "north-yorkshire"
        }
    ]
}
```

**Comment by BeardedSimmo** [comment]
Brill, thanks Shaun.  I'll give it a whirl and report back.

**Comment by BeardedSimmo** [comment]
Nearly there.  I have an on/off switch for the sky box now but none of the other features.
I have this text when homebridge is running
DRX890
500GB
R014.083.64.00P (4nplbg0)
376031545
undefined

Is there anything else that I could try?

**Comment by shauncampbell** [comment]
Thats a good sign... If you're using the default Apple home app - all you will see is an on/off switch. If you use something like Elgato Eve you'll be able to see the Channel Name/number and show there.

**Comment by shauncampbell** [comment]
What i've done is use another third party app called Home to create some scenes which let me manipulate the channel number and I've called them "Watch Sky One" and Siri will switch on the box for me if its not already on and change the channel.

**Comment by BeardedSimmo** [comment]
Wow!  'tis great!  Yep, can see all the detail (and currently what I'm watching on the planner) in the 3rd party 'home' app.  I hope this functionality eventually comes the the native 'Home' app as I struggle with scenes on iOS10 (my homebridge locks up requiring a restart) as I'm using an ATV3 as my hub.  It lost it's ability to run scenes/automation's with the upgrade to iOS 10 and until I 'upgrade' my iPad or ATV I have to run scenes through Domoticz.  Great plugin though and thanks for all your help this evening!

**Comment by shauncampbell** [comment]
Awesome :) Glad I could help!
