### ISSUE TITLE
Cant Install 

### ISSUE THREAD

**Issue by m11rphy** [shauncampbell/homebridge-sky-plus-hd#4]
Hi Shaun

I really want to try this out but getting the below issue trying to install this. I had another plugin controlling my sky box so not sure if thats the issue ?

$ npm install -g homebridge-sky-plus-hd
npm WARN addRemoteGit git+https://github.com/shauncampbell/sky-plus-hd.git#v1-dev resetting remote /Users/chrismurphy/.npm/_git-remotes/git-https-github-com-shauncampbell-sky-plus-hd-git-v1-dev-90a5023b because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm WARN addRemoteGit git+https://github.com/dalhundal/sky-remote.git resetting remote /Users/chrismurphy/.npm/_git-remotes/git-https-github-com-dalhundal-sky-remote-git-17457709 because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone --template=/Users/chrismurphy/.npm/_git-remotes/_templates --mirror https://github.com/shauncampbell/sky-plus-hd.git /Users/chrismurphy/.npm/_git-remotes/git-https-github-com-shauncampbell-sky-plus-hd-git-v1-dev-90a5023b: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone --template=/Users/chrismurphy/.npm/_git-remotes/_templates --mirror https://github.com/dalhundal/sky-remote.git /Users/chrismurphy/.npm/_git-remotes/git-https-github-com-dalhundal-sky-remote-git-17457709: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-sky-plus-hd"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code 1

npm ERR! Command failed: git clone --template=/Users/chrismurphy/.npm/_git-remotes/_templates --mirror https://github.com/shauncampbell/sky-plus-hd.git /Users/chrismurphy/.npm/_git-remotes/git-https-github-com-shauncampbell-sky-plus-hd-git-v1-dev-90a5023b
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by shauncampbell** [comment]
Hi there,  

From the error messages it looks to be an issue with your git installation. I'm sadly not an expert in this but I would try googling the error message and see if any of the situations apply to you.  

>  
> xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
>  


You could try doing a manual git clone as well and see what errors you get from that.

Cheers,  

Shaun

**Comment by m11rphy** [comment]
Had to format my mac but got it working now, its great plugin.
