### ISSUE TITLE
Channel Numbers 

### ISSUE THREAD

**Issue by m11rphy** [shauncampbell/homebridge-sky-plus-hd#5]
Hi Shaun 

Im so please with this plugin so thank you so much, I wanted to ask about creating scene and channel numbers. When I create a scene in Elgato Eve app I can only select certain channel numbers, for example I can select 412 and 414 but not 413 any ideas why ?

**Comment by shauncampbell** [comment]
Hey, sorry I only saw this now.

I think its just a crappy control thats been used in the Elgato Eve app. It would be nicer if there were a way to type in a number - i'll have a wee look and see if I can change the characteristic somewhat to allow a text field or something.

The Home app (not the apple one, the one thats about £10 on the iTunes store) uses a similar slider to Elgato, but it also provides + / - buttons, so I tend to use them. But its still not ideal I grant you :( I'll investigate over the weekend see if theres anything that can be done.
