### ISSUE TITLE
Germany

### ISSUE THREAD

**Issue by MarcusFischerSFN** [shauncampbell/homebridge-sky-plus-hd#9]
Hi, is it possible to use this plugin with non british sky receivers?
the region option is kind of a problem i think...

**Comment by shauncampbell** [comment]
As it stands probably not. The code is hard coded to look up program information from Sky UK’s site.  

I guess, if connectivity to the box is the same then you could change the code that corresponds to the program information to pull from a different resource.  

Unfortunately I don’t really have the means to test or implement this :(  

Out of curiosity do you know what the make and model of the Box you’re trying to connect to?

**Comment by MarcusFischerSFN** [comment]
Hi, as I saw that there is a closed issue on github I closed mine myself.

I will take a look at your code maybe I can figure out a solution…

Its a Humax S HD4.

Am 11.01.2018 um 02:17 schrieb Shaun Campbell <notifications@github.com<mailto:notifications@github.com>>:

As it stands probably not. The code is hard coded to look up program information from Sky UK’s site.

I guess, if connectivity to the box is the same then you could change the code that corresponds to the program information to pull from a different resource.

Unfortunately I don’t really have the means to test or implement this :(

Out of curiosity do you know what the make and model of the Box you’re trying to connect to?
